// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWP391.Entities;

#nullable disable

namespace SWP391.Migrations
{
    [DbContext(typeof(ScientificTrendDbContext))]
    [Migration("20260618040746_AddRevokedTokens")]
    partial class AddRevokedTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaperKeyword", b =>
                {
                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<int>("KeywordId")
                        .HasColumnType("int");

                    b.HasKey("PaperId", "KeywordId");

                    b.HasIndex(new[] { "KeywordId" }, "IX_PaperKeywords_KeywordId");

                    b.ToTable("PaperKeywords", (string)null);
                });

            modelBuilder.Entity("SWP391.Entities.ActivityLog", b =>
                {
                    b.Property<long>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActivityLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ActivityLogId");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_ActivityLogs_CreatedAt");

                    b.HasIndex(new[] { "UserId" }, "IX_ActivityLogs_UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("SWP391.Entities.ApiDataSource", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SourceId"));

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SourceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SourceId")
                        .HasName("PK__ApiDataS__16E0191954850B1E");

                    b.ToTable("ApiDataSources");
                });

            modelBuilder.Entity("SWP391.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("AuthorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResearchArea")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("TotalPublications")
                        .HasColumnType("int");

                    b.HasKey("AuthorId")
                        .HasName("PK__Authors__70DAFC347F30D68E");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("SWP391.Entities.Bookmark", b =>
                {
                    b.Property<long>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookmarkId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookmarkId")
                        .HasName("PK__Bookmark__541A3B71063868DC");

                    b.HasIndex(new[] { "UserId" }, "IX_Bookmarks_User");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("SWP391.Entities.DashboardReport", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportId"));

                    b.Property<string>("FilterConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReportType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReportId")
                        .HasName("PK__Dashboar__D5BD48054FB0E0D0");

                    b.HasIndex("UserId");

                    b.ToTable("DashboardReports");
                });

            modelBuilder.Entity("SWP391.Entities.EmailVerificationToken", b =>
                {
                    b.Property<long>("EmailVerificationTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmailVerificationTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmailVerificationTokenId");

                    b.HasIndex(new[] { "TokenHash" }, "IX_EmailVerificationTokens_TokenHash");

                    b.HasIndex(new[] { "UserId", "UsedAt" }, "IX_EmailVerificationTokens_User_UsedAt");

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("SWP391.Entities.Follow", b =>
                {
                    b.Property<long>("FollowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FollowId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FollowId")
                        .HasName("PK__Follows__2CE810AE40649A39");

                    b.HasIndex(new[] { "UserId" }, "IX_Follows_User");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("SWP391.Entities.GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleInGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GroupId", "UserId")
                        .HasName("PK__GroupMem__C5E27FAE44EE6647");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("SWP391.Entities.Journal", b =>
                {
                    b.Property<int>("JournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JournalId"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("ImpactFactor")
                        .HasColumnType("float");

                    b.Property<string>("Issn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ISSN");

                    b.Property<string>("JournalName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("JournalId")
                        .HasName("PK__Journals__250103E6EDD19799");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("SWP391.Entities.Keyword", b =>
                {
                    b.Property<int>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeywordId"));

                    b.Property<string>("KeywordText")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("KeywordId")
                        .HasName("PK__Keywords__37C13521B41C6024");

                    b.HasIndex(new[] { "KeywordText" }, "IX_Keywords_Text");

                    b.HasIndex(new[] { "TopicId" }, "IX_Keywords_TopicId");

                    b.HasIndex(new[] { "KeywordText" }, "UQ__Keywords__219EE3D704701796")
                        .IsUnique()
                        .HasFilter("[KeywordText] IS NOT NULL");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("SWP391.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RelatedId")
                        .HasColumnType("bigint");

                    b.Property<string>("RelatedType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12AD2102BE");

                    b.HasIndex(new[] { "UserId", "IsRead" }, "IX_Notifications_User");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SWP391.Entities.Paper", b =>
                {
                    b.Property<long>("PaperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaperId"));

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CitationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("JournalId")
                        .HasColumnType("int");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaperId")
                        .HasName("PK__Papers__AB86120B6AA80FBB");

                    b.HasIndex(new[] { "JournalId" }, "IX_Papers_JournalId");

                    b.HasIndex(new[] { "SourceId" }, "IX_Papers_SourceId");

                    b.HasIndex(new[] { "PublicationYear" }, "IX_Papers_Year");

                    b.ToTable("Papers");
                });

            modelBuilder.Entity("SWP391.Entities.PaperAuthor", b =>
                {
                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Affiliation")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("AuthorOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsCorresponding")
                        .HasColumnType("bit");

                    b.HasKey("PaperId", "AuthorId")
                        .HasName("PK__PaperAut__FC8BBDC843D72F9A");

                    b.HasIndex(new[] { "AuthorId" }, "IX_PaperAuthors_AuthorId");

                    b.ToTable("PaperAuthors", (string)null);
                });

            modelBuilder.Entity("SWP391.Entities.PaperCitation", b =>
                {
                    b.Property<long>("CitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CitationId"));

                    b.Property<long>("CitedPaperId")
                        .HasColumnType("bigint");

                    b.Property<long>("CitingPaperId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CitationId")
                        .HasName("PK__PaperCit__EAD2ADFB7C803DC4");

                    b.HasIndex("CitedPaperId");

                    b.HasIndex("CitingPaperId");

                    b.ToTable("PaperCitations");
                });

            modelBuilder.Entity("SWP391.Entities.PublicationTrend", b =>
                {
                    b.Property<long>("TrendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TrendId"));

                    b.Property<int?>("KeywordId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("PaperCount")
                        .HasColumnType("int");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<int?>("TrendYear")
                        .HasColumnType("int");

                    b.HasKey("TrendId")
                        .HasName("PK__Publicat__DACD10F79107C7D0");

                    b.HasIndex(new[] { "KeywordId" }, "IX_PublicationTrends_KeywordId");

                    b.HasIndex(new[] { "TrendYear" }, "IX_PublicationTrends_Year");

                    b.HasIndex(new[] { "TopicId", "TrendYear" }, "IX_Trends_TopicYear");

                    b.ToTable("PublicationTrends");
                });

            modelBuilder.Entity("SWP391.Entities.ResearchGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("GroupId")
                        .HasName("PK__Research__149AF36A1F2F87A7");

                    b.HasIndex("OwnerId");

                    b.ToTable("ResearchGroups");
                });

            modelBuilder.Entity("SWP391.Entities.ResearchTopic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TopicId")
                        .HasName("PK__Research__022E0F5D6DD9197C");

                    b.HasIndex(new[] { "TopicName" }, "UQ__Research__6C795E8C662E12F0")
                        .IsUnique()
                        .HasFilter("[TopicName] IS NOT NULL");

                    b.ToTable("ResearchTopics");
                });

            modelBuilder.Entity("SWP391.Entities.RevokedToken", b =>
                {
                    b.Property<long>("RevokedTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RevokedTokenId"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RevokedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RevokedTokenId");

                    b.HasIndex(new[] { "ExpiresAt" }, "IX_RevokedTokens_ExpiresAt");

                    b.HasIndex(new[] { "TokenHash" }, "IX_RevokedTokens_TokenHash")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_RevokedTokens_UserId");

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("SWP391.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1AAEFBCBC7");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B61607F418F30")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Administrator"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Researcher"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Member"
                        });
                });

            modelBuilder.Entity("SWP391.Entities.SyncJob", b =>
                {
                    b.Property<long>("SyncJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SyncJobId"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordsFetched")
                        .HasColumnType("int");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SyncJobId")
                        .HasName("PK__SyncJobs__1078C047AFB584C5");

                    b.HasIndex(new[] { "SourceId" }, "IX_SyncJobs_SourceId");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("SWP391.Entities.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingKey")
                        .HasName("PK__SystemSe__01E719AC4ECCE7D3");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("SWP391.Entities.TrendSnapshot", b =>
                {
                    b.Property<long>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SnapshotId"));

                    b.Property<double>("CitationVelocity")
                        .HasColumnType("float");

                    b.Property<double>("GrowthRate")
                        .HasColumnType("float");

                    b.Property<int?>("KeywordId")
                        .HasColumnType("int");

                    b.Property<double>("Momentum")
                        .HasColumnType("float");

                    b.Property<int>("PaperCount")
                        .HasColumnType("int");

                    b.Property<int>("RecentPaperCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<double>("TrendScore")
                        .HasColumnType("float");

                    b.HasKey("SnapshotId");

                    b.HasIndex(new[] { "SnapshotDate" }, "IX_TrendSnapshots_Date");

                    b.HasIndex(new[] { "KeywordId", "SnapshotDate" }, "IX_TrendSnapshots_Keyword_Date");

                    b.HasIndex(new[] { "TopicId", "SnapshotDate" }, "IX_TrendSnapshots_Topic_Date");

                    b.ToTable("TrendSnapshots");
                });

            modelBuilder.Entity("SWP391.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Student");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CABBA0262");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105340115A41D")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SWP391.Entities.UserPreference", b =>
                {
                    b.Property<long>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PreferenceId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PreferredField")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PreferredYearRange")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PreferenceId")
                        .HasName("PK__UserPref__E228496F80308D5A");

                    b.HasIndex("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_UserRoles_RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("PaperKeyword", b =>
                {
                    b.HasOne("SWP391.Entities.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PaperKeyw__Keywo__46E78A0C");

                    b.HasOne("SWP391.Entities.Paper", null)
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PaperKeyw__Paper__45F365D3");
                });

            modelBuilder.Entity("SWP391.Entities.ActivityLog", b =>
                {
                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391.Entities.Bookmark", b =>
                {
                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Bookmarks__UserI__4F7CD00D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391.Entities.DashboardReport", b =>
                {
                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany("DashboardReports")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Dashboard__UserI__5070F446");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391.Entities.Follow", b =>
                {
                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany("Follows")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Follows__UserId__534D60F1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391.Entities.GroupMember", b =>
                {
                    b.HasOne("SWP391.Entities.ResearchGroup", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupMemb__Group__68487DD7");

                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupMemb__UserI__693CA210");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391.Entities.Keyword", b =>
                {
                    b.HasOne("SWP391.Entities.ResearchTopic", "Topic")
                        .WithMany("Keywords")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("FK__Keywords__TopicI__4316F928");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SWP391.Entities.Notification", b =>
                {
                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__5812160E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391.Entities.Paper", b =>
                {
                    b.HasOne("SWP391.Entities.Journal", "Journal")
                        .WithMany("Papers")
                        .HasForeignKey("JournalId")
                        .HasConstraintName("FK__Papers__JournalI__35BCFE0A");

                    b.HasOne("SWP391.Entities.ApiDataSource", "Source")
                        .WithMany("Papers")
                        .HasForeignKey("SourceId")
                        .HasConstraintName("FK__Papers__SourceId__36B12243");

                    b.Navigation("Journal");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SWP391.Entities.PaperAuthor", b =>
                {
                    b.HasOne("SWP391.Entities.Author", "Author")
                        .WithMany("PaperAuthors")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__PaperAuth__Autho__3C69FB99");

                    b.HasOne("SWP391.Entities.Paper", "Paper")
                        .WithMany("PaperAuthors")
                        .HasForeignKey("PaperId")
                        .IsRequired()
                        .HasConstraintName("FK__PaperAuth__Paper__3B75D760");

                    b.Navigation("Author");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("SWP391.Entities.PaperCitation", b =>
                {
                    b.HasOne("SWP391.Entities.Paper", "CitedPaper")
                        .WithMany("PaperCitationCitedPapers")
                        .HasForeignKey("CitedPaperId")
                        .IsRequired()
                        .HasConstraintName("FK__PaperCita__Cited__628FA481");

                    b.HasOne("SWP391.Entities.Paper", "CitingPaper")
                        .WithMany("PaperCitationCitingPapers")
                        .HasForeignKey("CitingPaperId")
                        .IsRequired()
                        .HasConstraintName("FK__PaperCita__Citin__619B8048");

                    b.Navigation("CitedPaper");

                    b.Navigation("CitingPaper");
                });

            modelBuilder.Entity("SWP391.Entities.PublicationTrend", b =>
                {
                    b.HasOne("SWP391.Entities.Keyword", "Keyword")
                        .WithMany("PublicationTrends")
                        .HasForeignKey("KeywordId")
                        .HasConstraintName("FK__Publicati__Keywo__4BAC3F29");

                    b.HasOne("SWP391.Entities.ResearchTopic", "Topic")
                        .WithMany("PublicationTrends")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("FK__Publicati__Topic__4AB81AF0");

                    b.Navigation("Keyword");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SWP391.Entities.ResearchGroup", b =>
                {
                    b.HasOne("SWP391.Entities.User", "Owner")
                        .WithMany("ResearchGroups")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__ResearchG__Owner__656C112C");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SWP391.Entities.RevokedToken", b =>
                {
                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany("RevokedTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391.Entities.SyncJob", b =>
                {
                    b.HasOne("SWP391.Entities.ApiDataSource", "Source")
                        .WithMany("SyncJobs")
                        .HasForeignKey("SourceId")
                        .HasConstraintName("FK__SyncJobs__Source__5AEE82B9");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SWP391.Entities.TrendSnapshot", b =>
                {
                    b.HasOne("SWP391.Entities.Keyword", "Keyword")
                        .WithMany("TrendSnapshots")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SWP391.Entities.ResearchTopic", "Topic")
                        .WithMany("TrendSnapshots")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Keyword");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SWP391.Entities.UserPreference", b =>
                {
                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany("UserPreferences")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__UserPrefe__UserI__2E1BDC42");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("SWP391.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__RoleI__2D27B809");

                    b.HasOne("SWP391.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__UserI__2C3393D0");
                });

            modelBuilder.Entity("SWP391.Entities.ApiDataSource", b =>
                {
                    b.Navigation("Papers");

                    b.Navigation("SyncJobs");
                });

            modelBuilder.Entity("SWP391.Entities.Author", b =>
                {
                    b.Navigation("PaperAuthors");
                });

            modelBuilder.Entity("SWP391.Entities.Journal", b =>
                {
                    b.Navigation("Papers");
                });

            modelBuilder.Entity("SWP391.Entities.Keyword", b =>
                {
                    b.Navigation("PublicationTrends");

                    b.Navigation("TrendSnapshots");
                });

            modelBuilder.Entity("SWP391.Entities.Paper", b =>
                {
                    b.Navigation("PaperAuthors");

                    b.Navigation("PaperCitationCitedPapers");

                    b.Navigation("PaperCitationCitingPapers");
                });

            modelBuilder.Entity("SWP391.Entities.ResearchGroup", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("SWP391.Entities.ResearchTopic", b =>
                {
                    b.Navigation("Keywords");

                    b.Navigation("PublicationTrends");

                    b.Navigation("TrendSnapshots");
                });

            modelBuilder.Entity("SWP391.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Bookmarks");

                    b.Navigation("DashboardReports");

                    b.Navigation("Follows");

                    b.Navigation("GroupMembers");

                    b.Navigation("Notifications");

                    b.Navigation("ResearchGroups");

                    b.Navigation("RevokedTokens");

                    b.Navigation("UserPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
