// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWP391.Entities;

#nullable disable

namespace SWP391.Migrations
{
    [DbContext(typeof(ScientificTrendDbContext))]
    [Migration("20260605122510_AddUserActorType")]
    partial class AddUserActorType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaperAuthor", b =>
                {
                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("PaperId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("PaperAuthors", (string)null);
                });

            modelBuilder.Entity("PaperKeyword", b =>
                {
                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<int>("KeywordId")
                        .HasColumnType("int");

                    b.HasKey("PaperId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("PaperKeywords", (string)null);
                });

            modelBuilder.Entity("SWP391.Entities.ApiDataSource", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SourceId"));

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SourceId")
                        .HasName("PK__ApiDataS__16E0191954850B1E");

                    b.ToTable("ApiDataSources");
                });

            modelBuilder.Entity("SWP391.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AuthorId")
                        .HasName("PK__Authors__70DAFC347F30D68E");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("SWP391.Entities.Bookmark", b =>
                {
                    b.Property<long>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookmarkId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookmarkId")
                        .HasName("PK__Bookmark__541A3B71063868DC");

                    b.HasIndex(new[] { "UserId" }, "IX_Bookmarks_User");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("SWP391.Entities.EmailVerificationToken", b =>
                {
                    b.Property<long>("EmailVerificationTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmailVerificationTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmailVerificationTokenId");

                    b.HasIndex(new[] { "TokenHash" }, "IX_EmailVerificationTokens_TokenHash");

                    b.HasIndex(new[] { "UserId", "UsedAt" }, "IX_EmailVerificationTokens_User_UsedAt");

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("SWP391.Entities.Follow", b =>
                {
                    b.Property<long>("FollowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FollowId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FollowId")
                        .HasName("PK__Follows__2CE810AE40649A39");

                    b.HasIndex(new[] { "UserId" }, "IX_Follows_User");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("SWP391.Entities.Journal", b =>
                {
                    b.Property<int>("JournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JournalId"));

                    b.Property<string>("Issn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ISSN");

                    b.Property<string>("JournalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("JournalId")
                        .HasName("PK__Journals__250103E6EDD19799");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("SWP391.Entities.Keyword", b =>
                {
                    b.Property<int>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeywordId"));

                    b.Property<string>("KeywordText")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("KeywordId")
                        .HasName("PK__Keywords__37C13521B41C6024");

                    b.HasIndex("TopicId");

                    b.HasIndex(new[] { "KeywordText" }, "IX_Keywords_Text");

                    b.HasIndex(new[] { "KeywordText" }, "UQ__Keywords__219EE3D704701796")
                        .IsUnique();

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("SWP391.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RelatedId")
                        .HasColumnType("bigint");

                    b.Property<string>("RelatedType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12AD2102BE");

                    b.HasIndex(new[] { "UserId", "IsRead" }, "IX_Notifications_User");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SWP391.Entities.Paper", b =>
                {
                    b.Property<long>("PaperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaperId"));

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CitationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("JournalId")
                        .HasColumnType("int");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaperId")
                        .HasName("PK__Papers__AB86120B6AA80FBB");

                    b.HasIndex("JournalId");

                    b.HasIndex("SourceId");

                    b.HasIndex(new[] { "PublicationYear" }, "IX_Papers_Year");

                    b.ToTable("Papers");
                });

            modelBuilder.Entity("SWP391.Entities.PublicationTrend", b =>
                {
                    b.Property<long>("TrendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TrendId"));

                    b.Property<int?>("KeywordId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("PaperCount")
                        .HasColumnType("int");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("TrendYear")
                        .HasColumnType("int");

                    b.HasKey("TrendId")
                        .HasName("PK__Publicat__DACD10F79107C7D0");

                    b.HasIndex("KeywordId");

                    b.HasIndex(new[] { "TrendYear" }, "IX_PublicationTrends_Year");

                    b.HasIndex(new[] { "TopicId", "TrendYear" }, "IX_Trends_TopicYear");

                    b.ToTable("PublicationTrends");
                });

            modelBuilder.Entity("SWP391.Entities.ResearchTopic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TopicId")
                        .HasName("PK__Research__022E0F5D6DD9197C");

                    b.HasIndex(new[] { "TopicName" }, "UQ__Research__6C795E8C662E12F0")
                        .IsUnique();

                    b.ToTable("ResearchTopics");
                });

            modelBuilder.Entity("SWP391.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1AAEFBCBC7");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B61607F418F30")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Administrator"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Researcher"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Member"
                        });
                });

            modelBuilder.Entity("SWP391.Entities.SyncJob", b =>
                {
                    b.Property<long>("SyncJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SyncJobId"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordsFetched")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SyncJobId")
                        .HasName("PK__SyncJobs__1078C047AFB584C5");

                    b.HasIndex("SourceId");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("SWP391.Entities.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingKey")
                        .HasName("PK__SystemSe__01E719AC4ECCE7D3");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("SWP391.Entities.TrendSnapshot", b =>
                {
                    b.Property<long>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SnapshotId"));

                    b.Property<double>("CitationVelocity")
                        .HasColumnType("float");

                    b.Property<double>("GrowthRate")
                        .HasColumnType("float");

                    b.Property<int?>("KeywordId")
                        .HasColumnType("int");

                    b.Property<double>("Momentum")
                        .HasColumnType("float");

                    b.Property<int>("PaperCount")
                        .HasColumnType("int");

                    b.Property<int>("RecentPaperCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<double>("TrendScore")
                        .HasColumnType("float");

                    b.HasKey("SnapshotId");

                    b.HasIndex(new[] { "SnapshotDate" }, "IX_TrendSnapshots_Date");

                    b.HasIndex(new[] { "KeywordId", "SnapshotDate" }, "IX_TrendSnapshots_Keyword_Date");

                    b.HasIndex(new[] { "TopicId", "SnapshotDate" }, "IX_TrendSnapshots_Topic_Date");

                    b.ToTable("TrendSnapshots");
                });

            modelBuilder.Entity("SWP391.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Student");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CABBA0262");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105340115A41D")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("PaperAuthor", b =>
                {
                    b.HasOne("SWP391.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PaperAuth__Autho__3C69FB99");

                    b.HasOne("SWP391.Entities.Paper", null)
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PaperAuth__Paper__3B75D760");
                });

            modelBuilder.Entity("PaperKeyword", b =>
                {
                    b.HasOne("SWP391.Entities.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PaperKeyw__Keywo__46E78A0C");

                    b.HasOne("SWP391.Entities.Paper", null)
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PaperKeyw__Paper__45F365D3");
                });

            modelBuilder.Entity("SWP391.Entities.Bookmark", b =>
                {
                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Bookmarks__UserI__4F7CD00D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391.Entities.Follow", b =>
                {
                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany("Follows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Follows__UserId__534D60F1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391.Entities.Keyword", b =>
                {
                    b.HasOne("SWP391.Entities.ResearchTopic", "Topic")
                        .WithMany("Keywords")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("FK__Keywords__TopicI__4316F928");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SWP391.Entities.Notification", b =>
                {
                    b.HasOne("SWP391.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__5812160E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391.Entities.Paper", b =>
                {
                    b.HasOne("SWP391.Entities.Journal", "Journal")
                        .WithMany("Papers")
                        .HasForeignKey("JournalId")
                        .HasConstraintName("FK__Papers__JournalI__35BCFE0A");

                    b.HasOne("SWP391.Entities.ApiDataSource", "Source")
                        .WithMany("Papers")
                        .HasForeignKey("SourceId")
                        .HasConstraintName("FK__Papers__SourceId__36B12243");

                    b.Navigation("Journal");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SWP391.Entities.PublicationTrend", b =>
                {
                    b.HasOne("SWP391.Entities.Keyword", "Keyword")
                        .WithMany("PublicationTrends")
                        .HasForeignKey("KeywordId")
                        .HasConstraintName("FK__Publicati__Keywo__4BAC3F29");

                    b.HasOne("SWP391.Entities.ResearchTopic", "Topic")
                        .WithMany("PublicationTrends")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("FK__Publicati__Topic__4AB81AF0");

                    b.Navigation("Keyword");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SWP391.Entities.SyncJob", b =>
                {
                    b.HasOne("SWP391.Entities.ApiDataSource", "Source")
                        .WithMany("SyncJobs")
                        .HasForeignKey("SourceId")
                        .IsRequired()
                        .HasConstraintName("FK__SyncJobs__Source__5AEE82B9");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SWP391.Entities.TrendSnapshot", b =>
                {
                    b.HasOne("SWP391.Entities.Keyword", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SWP391.Entities.ResearchTopic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Keyword");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("SWP391.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__RoleI__2D27B809");

                    b.HasOne("SWP391.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__UserI__2C3393D0");
                });

            modelBuilder.Entity("SWP391.Entities.ApiDataSource", b =>
                {
                    b.Navigation("Papers");

                    b.Navigation("SyncJobs");
                });

            modelBuilder.Entity("SWP391.Entities.Journal", b =>
                {
                    b.Navigation("Papers");
                });

            modelBuilder.Entity("SWP391.Entities.Keyword", b =>
                {
                    b.Navigation("PublicationTrends");
                });

            modelBuilder.Entity("SWP391.Entities.ResearchTopic", b =>
                {
                    b.Navigation("Keywords");

                    b.Navigation("PublicationTrends");
                });

            modelBuilder.Entity("SWP391.Entities.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Follows");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
